### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '..\\cache\\waterML_GetCapabilities.json'

### ISSUE THREAD

**Issue by jmp75** [csiro-hydroinformatics/bomwater-notebook#1]
Caching may be useful but should not be a relative directory.
Issue located in the package not the notebook.

**Comment by fre171csiro** [comment]
@jmp75 if you have a moment can you check https://github.com/csiro-hydroinformatics/bomwater-notebook/commit/e9e734fdb3d1c3bad6fe187124ef817ebe320159 I think I have resolved this issue
